image: 
  name: intravisor/cheri-sdk:2405
  entrypoint: ['bash', '-c', 'exec su cheri -c bash']

stages:
- build_intravisor
- build_runtime
- build_app
- run_app

include:
 - 'extras/.gitlab-ci-pure-arm2.yml'
# - 'extras/.gitlab-ci-pure-arm.yml'
# - 'extras/.gitlab-ci-pure-rv.yml'
# - 'extras/.gitlab-ci-lkl-arm.yml'
# - 'extras/.gitlab-ci-lkl-rv.yml'
# - 'extras/.gitlab-ci-orc-arm.yml'
# - 'extras/.gitlab-ci-native-arm.yml'
# - 'extras/.gitlab-ci-native-rv.yml'
